version: '3.5'
services:
  api1: # API - Instância 01
    build: .
    environment:
      HTTP_PORT: 3000
      POOL_SIZE: 50
    network_mode: host
    depends_on:
      - db
    ulimits:
      nproc: 1000000
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '100MB'

  api2: # API - Instância 01
    build: .
    environment:
      HTTP_PORT: 3001
      POOL_SIZE: 50
    network_mode: host
    depends_on:
      - db
    ulimits:
      nproc: 1000000
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '100MB'

  nginx: # Load Balancer
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '37MB'

  db: # Banco de dados
    image: postgres
    hostname: database
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgresql.conf:/docker-entrypoint-initdb.d/postgresql.conf
    command: postgres -c config_file=/docker-entrypoint-initdb.d/postgresql.conf
    network_mode: host
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: rinhadb
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: '275MB'
